import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
// ignore: depend_on_referenced_packages
import 'package:flutter_web_plugins/url_strategy.dart';
import 'package:http/http.dart' as http;
import 'package:kerosene/core/config/app_config.dart';
import 'package:kerosene/core/copy/kerosene_ui_copy.dart';
import 'package:kerosene/core/l10n/app_localizations.dart';
import 'package:kerosene/core/navigation/deferred_page.dart';
import 'package:kerosene/core/navigation/app_page_transitions.dart';
import 'package:kerosene/core/performance/kerosene_performance_boundary.dart';
import 'package:kerosene/core/providers/session_invalidation_provider.dart';
import 'package:kerosene/core/providers/tor_providers.dart';
import 'package:kerosene/core/responsive/kerosene_responsive.dart';
import 'package:kerosene/core/theme/app_typography.dart';
import 'package:kerosene/core/theme/kerosene_brand_tokens.dart';
import 'package:kerosene/features/auth/controller/auth_controller.dart';
import 'package:kerosene/features/web/theme/admin_theme.dart';
import 'package:kerosene/features/auth/presentation/screens/server_unavailable_screen.dart'
    deferred as server_unavailable;
import 'package:kerosene/features/landing/presentation/kerosene_landing_page.dart'
    deferred as landing;
import 'package:kerosene/features/web/navigation/admin_content_router.dart'
    deferred as admin_content_router;
import 'package:kerosene/features/web/screens/login/admin_login_screen.dart'
    deferred as admin_login;
import 'package:kerosene/features/web/shell/admin_shell.dart'
    deferred as admin_shell;

typedef RuntimeConfigReader = Future<Map<String, dynamic>?> Function(
  Uri configUri,
);
typedef ApiHealthProbe = Future<bool> Function(Uri healthUri);

const _runtimeConfigPath = '/kerosene-runtime-config.json';
const _localApiProbeTimeout = Duration(milliseconds: 700);
const _wellKnownLocalApiPorts = <int>[
  3000,
  8080,
  30080,
  30082,
  8081,
  8082,
];

/// Resolves the API URL for the web admin.
///
/// Priority order:
/// 1. `WEB_API_URL` compile-time env → e.g. `http://xyz.onion` via an onion gateway
/// 2. `WEB_ONION_GATEWAY` compile-time env → an HTTP gateway that proxies to .onion
/// 3. Same-origin runtime config generated by local startup scripts
/// 4. If the browser is already on a .onion domain (via Tor Browser), use the origin
/// 5. Local-loopback health probes for common Kerosene ports
/// 6. Fallback to `Uri.base.origin` (same-origin for clearnet deployments)
@visibleForTesting
Future<String> resolveApiUrlForWeb({
  Uri? browserUri,
  RuntimeConfigReader? runtimeConfigReader,
  ApiHealthProbe? apiHealthProbe,
}) async {
  final currentUri = browserUri ?? Uri.base;

  // 1. Explicit API URL override (highest priority)
  const configuredApiUrl = String.fromEnvironment('WEB_API_URL');
  if (configuredApiUrl.trim().isNotEmpty) {
    return _normalizeApiOrigin(configuredApiUrl, 'WEB_API_URL');
  }

  // 2. Onion gateway proxy URL (e.g. onion2web, tor2web, or local Nginx)
  const onionGateway = String.fromEnvironment('WEB_ONION_GATEWAY');
  if (onionGateway.trim().isNotEmpty) {
    return _normalizeApiOrigin(onionGateway, 'WEB_ONION_GATEWAY');
  }

  final runtimeApiUrl = await _readRuntimeConfiguredApiUrl(
    currentUri,
    runtimeConfigReader ?? _defaultRuntimeConfigReader,
  );
  if (runtimeApiUrl != null) {
    return runtimeApiUrl;
  }

  // 4. Detect if already running inside Tor Browser on a .onion domain
  try {
    final origin = currentUri.origin;
    final host = currentUri.host;
    if (host.endsWith('.onion')) {
      debugPrint('🧅 Detected .onion origin: $origin');
      return origin;
    }
  } catch (_) {}

  if (_isLocalBrowserOrigin(currentUri)) {
    final localApiUrl = await _discoverLocalApiUrl(
      currentUri,
      apiHealthProbe ?? _defaultApiHealthProbe,
    );
    if (localApiUrl != null) {
      return localApiUrl;
    }
  }

  // 6. Same-origin fallback (web app served by the backend/proxy itself)
  return currentUri.origin;
}

String _normalizeApiOrigin(String raw, String envName) {
  final trimmed = raw.trim();
  final uri = Uri.tryParse(trimmed);
  if (uri == null || !uri.hasScheme || uri.host.trim().isEmpty) {
    throw ArgumentError(
      '$envName must be an absolute URL, for example http://example.onion',
    );
  }

  if (uri.scheme != 'http' && uri.scheme != 'https') {
    throw ArgumentError('$envName must use http or https.');
  }

  return trimmed.endsWith('/')
      ? trimmed.substring(0, trimmed.length - 1)
      : trimmed;
}

bool _isOnionHost(String host) => host.toLowerCase().endsWith('.onion');

bool _isLoopbackHost(String host) {
  final normalized = host.toLowerCase();
  return normalized == 'localhost' ||
      normalized == '127.0.0.1' ||
      normalized == '::1' ||
      normalized == '[::1]';
}

bool _isLocalBrowserOrigin(Uri uri) {
  return (uri.scheme == 'http' || uri.scheme == 'https') &&
      _isLoopbackHost(uri.host);
}

bool _sameOrigin(Uri left, Uri right) {
  return left.scheme == right.scheme &&
      left.host.toLowerCase() == right.host.toLowerCase() &&
      left.port == right.port;
}

Future<Map<String, dynamic>?> _defaultRuntimeConfigReader(Uri configUri) async {
  try {
    final response = await http.get(configUri, headers: const {
      'Accept': 'application/json'
    }).timeout(_localApiProbeTimeout);
    if (response.statusCode != 200) {
      return null;
    }

    final decoded = jsonDecode(response.body);
    return decoded is Map<String, dynamic> ? decoded : null;
  } catch (_) {
    return null;
  }
}

Future<String?> _readRuntimeConfiguredApiUrl(
  Uri browserUri,
  RuntimeConfigReader reader,
) async {
  final configUri = browserUri.replace(
    path: _runtimeConfigPath,
    query: null,
    fragment: null,
  );

  final config = await reader(configUri);
  final rawApiUrl = config?['apiUrl'];
  if (rawApiUrl is! String || rawApiUrl.trim().isEmpty) {
    return null;
  }

  try {
    final normalized = _normalizeApiOrigin(
      rawApiUrl,
      '$_runtimeConfigPath apiUrl',
    );
    final apiUri = Uri.parse(normalized);
    if (_sameOrigin(apiUri, browserUri) ||
        _isOnionHost(apiUri.host) ||
        (_isLoopbackHost(browserUri.host) && _isLoopbackHost(apiUri.host))) {
      return normalized;
    }
  } catch (error) {
    debugPrint('Ignoring invalid runtime API config: $error');
    return null;
  }

  debugPrint('Ignoring untrusted runtime API config host: $rawApiUrl');
  return null;
}

Future<bool> _defaultApiHealthProbe(Uri healthUri) async {
  try {
    final response = await http.get(healthUri, headers: const {
      'Accept': 'application/json'
    }).timeout(_localApiProbeTimeout);
    if (response.statusCode != 200 && response.statusCode != 503) {
      return false;
    }

    final decoded = jsonDecode(response.body);
    return decoded is Map &&
        decoded['service'] != null &&
        decoded['status'] != null;
  } catch (_) {
    return false;
  }
}

Future<String?> _discoverLocalApiUrl(
  Uri browserUri,
  ApiHealthProbe apiHealthProbe,
) async {
  for (final origin in _localApiCandidateOrigins(browserUri)) {
    final healthUri = Uri.parse(origin).replace(path: '/health/ready');
    if (await apiHealthProbe(healthUri)) {
      return origin;
    }
  }
  return null;
}

@visibleForTesting
List<String> localApiCandidateOrigins(Uri browserUri) {
  return _localApiCandidateOrigins(browserUri);
}

List<String> _localApiCandidateOrigins(Uri browserUri) {
  final hosts = <String>[
    browserUri.host,
    if (browserUri.host == 'localhost') '127.0.0.1',
    if (browserUri.host == '127.0.0.1') 'localhost',
  ];
  final ports = <int>[
    if (browserUri.hasPort) browserUri.port,
    ..._wellKnownLocalApiPorts,
  ];

  final origins = <String>{};
  for (final host in hosts.where(_isLoopbackHost)) {
    for (final port in ports.where((port) => port > 0)) {
      origins.add(Uri(scheme: 'http', host: host, port: port).origin);
    }
  }
  return origins.toList(growable: false);
}

Future<void> initializeApp(ProviderContainer container) async {
  usePathUrlStrategy();

  final resolvedApiUrl = await resolveApiUrlForWeb();
  debugPrint('🌐 Web Admin API URL: $resolvedApiUrl');

  configureResolvedApiUrl(container, resolvedApiUrl);
}

@visibleForTesting
void configureResolvedApiUrl(
  ProviderContainer container,
  String resolvedApiUrl,
) {
  // Web requests go directly to the resolved origin. Keep the logical active
  // node aligned with that host so passkey rpId/authenticatorData validation
  // uses the same host the backend actually receives.
  AppConfig.apiUrl = resolvedApiUrl;
  AppConfig.activeNodeUrl = resolvedApiUrl;

  try {
    final host = Uri.parse(resolvedApiUrl).host;
    final browserHost = Uri.base.host;
    AppConfig.isTorEnabled = _isOnionHost(host) || _isOnionHost(browserHost);
    if (_isOnionHost(host)) {
      debugPrint('🧅 Onion routing active → $host');
    }
  } catch (_) {}

  container.read(torApiUrlProvider.notifier).updateUrl(resolvedApiUrl);
}

Widget buildApp() => const _AdminWebApp();

class _AdminWebApp extends ConsumerWidget {
  const _AdminWebApp();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.listen<int>(sessionInvalidationProvider, (previous, next) {
      if (previous == next) {
        return;
      }
      ref.read(authControllerProvider.notifier).markSessionInvalidated();
    });

    return MaterialApp(
      title: 'Kerosene',
      debugShowCheckedModeBanner: false,
      theme: AdminTheme.themeData.copyWith(
        pageTransitionsTheme: kerosenePageTransitionsTheme,
      ),
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      scrollBehavior: const _WebScrollBehavior(),
      builder: (context, child) {
        return KeroseneResponsiveBoundary(
          child: KerosenePerformanceBoundary(child: child!),
        );
      },
      initialRoute: _initialRoute(),
      routes: {
        '/': (_) => DeferredPage(
              loadLibrary: landing.loadLibrary,
              builder: (_) => landing.KeroseneLandingPage(),
            ),
        '/bitcoin-banking': (_) => DeferredPage(
              loadLibrary: landing.loadLibrary,
              builder: (_) => landing.KeroseneLandingPage(),
            ),
        '/admin': (_) => const _AdminAuthGate(),
        '/download': (_) => DeferredPage(
              loadLibrary: landing.loadLibrary,
              builder: (_) => landing.KeroseneLandingPage(focusDownload: true),
            ),
        '/status': (_) => DeferredPage(
              loadLibrary: landing.loadLibrary,
              builder: (_) => landing.KerosenePublicStatusPage(),
            ),
      },
      onUnknownRoute: (_) => MaterialPageRoute(
        builder: (_) => DeferredPage(
          loadLibrary: landing.loadLibrary,
          builder: (_) => landing.KeroseneLandingPage(),
        ),
      ),
    );
  }

  String _initialRoute() {
    return resolveWebInitialRoute(Uri.base.path);
  }
}

@visibleForTesting
String resolveWebInitialRoute(String path) {
  if (path == '/bitcoin-banking' || path.startsWith('/bitcoin-banking/')) {
    return '/bitcoin-banking';
  }
  if (path == '/admin' || path.startsWith('/admin/')) return '/admin';
  if (path == '/download') return '/download';
  if (path == '/status') return '/status';
  return '/';
}

class _AdminAuthGate extends ConsumerWidget {
  const _AdminAuthGate();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authControllerProvider);

    if (authState is AuthInitial || authState is AuthLoading) {
      return const Scaffold(
        backgroundColor: KeroseneBrandTokens.backgroundSoft,
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              SizedBox(
                width: 24,
                height: 24,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  color: KeroseneBrandTokens.textMuted,
                ),
              ),
              SizedBox(height: 16),
              Text(
                KeroseneUiCopy.secureConnectionLoading,
                style: TextStyle(
                  fontFamily: AppTypography.financialFontFamily,
                  fontSize: 12,
                  color: KeroseneBrandTokens.textMuted,
                ),
              ),
            ],
          ),
        ),
      );
    }

    if (authState is AuthAuthenticated && authState.user.isAdmin) {
      return DeferredPage(
        loadLibrary: _loadAdminSurface,
        builder: (_) => admin_shell.AdminShell(
          child: admin_content_router.AdminContentRouter(),
        ),
      );
    }

    if (authState is AuthRequiresLoginTotp) {
      return DeferredPage(
        loadLibrary: admin_login.loadLibrary,
        builder: (_) => admin_login.AdminLoginScreen(),
      );
    }

    if (authState is AuthServerUnavailable) {
      return _ServerUnavailableView(message: authState.message, ref: ref);
    }

    return DeferredPage(
      loadLibrary: admin_login.loadLibrary,
      builder: (_) => admin_login.AdminLoginScreen(),
    );
  }
}

class _ServerUnavailableView extends StatelessWidget {
  final String message;
  final WidgetRef ref;

  const _ServerUnavailableView({required this.message, required this.ref});

  @override
  Widget build(BuildContext context) {
    return DeferredPage(
      loadLibrary: server_unavailable.loadLibrary,
      builder: (_) => server_unavailable.ServerUnavailableScreen(
        message: message,
        onRetryOverride: () {
          return ref.read(authControllerProvider.notifier).retrySessionCheck();
        },
      ),
    );
  }
}

Future<void> _loadAdminSurface() async {
  await Future.wait<void>([
    admin_shell.loadLibrary(),
    admin_content_router.loadLibrary(),
  ]);
}

class _WebScrollBehavior extends ScrollBehavior {
  const _WebScrollBehavior();

  @override
  ScrollPhysics getScrollPhysics(BuildContext context) {
    return const ClampingScrollPhysics();
  }
}
