import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter/material.dart';

class NotificationService {
  static final NotificationService _instance = NotificationService._internal();
  static const String _updatesChannelId = 'kerosene_updates';
  bool _isInitialized = false;

  factory NotificationService() {
    return _instance;
  }

  NotificationService._internal();

  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  Future<void> init() async {
    if (_isInitialized) {
      return;
    }

    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/launcher_icon');

    const DarwinInitializationSettings initializationSettingsDarwin =
        DarwinInitializationSettings(
      requestSoundPermission: false,
      requestBadgePermission: false,
      requestAlertPermission: false,
    );

    const InitializationSettings initializationSettings =
        InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsDarwin,
    );

    await flutterLocalNotificationsPlugin.initialize(
      settings: initializationSettings,
    );

    const AndroidNotificationChannel updatesChannel =
        AndroidNotificationChannel(
      _updatesChannelId,
      'Kerosene Alerts',
      description: 'Transaction and security alerts generated by Kerosene',
      importance: Importance.high,
    );

    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(updatesChannel);

    _isInitialized = true;
  }

  Future<bool> requestPermissions() async {
    await init();

    var granted = true;

    final iosImplementation =
        flutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin>();
    if (iosImplementation != null) {
      granted = granted &&
          (await iosImplementation.requestPermissions(
                alert: true,
                badge: true,
                sound: true,
              ) ??
              false);
    }

    final androidImplementation =
        flutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>();
    if (androidImplementation != null) {
      granted = granted &&
          (await androidImplementation.requestNotificationsPermission() ??
              true);
    }

    return granted;
  }

  Future<void> showSubtleNotification({
    required int id,
    required String title,
    required String body,
  }) async {
    await init();

    final normalizedTitle = _normalizeText(title, fallback: 'Kerosene');
    final normalizedBody = _normalizeText(body);

    final AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails(
      _updatesChannelId,
      'Kerosene Alerts',
      channelDescription: 'Direct transaction and security alerts',
      importance: Importance.max, // MAX for Heads-up
      priority: Priority.high,
      showWhen: true,
      color: const Color(0xFFC4CAD1),
      colorized: false,
      ticker: normalizedTitle,
      subText: 'Kerosene',
      visibility: NotificationVisibility.public, // Show content on lock screen
      category: AndroidNotificationCategory.status,
      styleInformation: BigTextStyleInformation(
        normalizedBody,
        contentTitle: normalizedTitle,
      ),
      playSound: true,
      enableVibration: true,
    );

    final NotificationDetails notificationDetails = NotificationDetails(
      android: androidNotificationDetails,
      iOS: const DarwinNotificationDetails(
        presentAlert: true,
        presentBadge: true,
        presentSound: true,
        presentBanner: true,
        presentList: true,
        threadIdentifier: 'kerosene_push',
        interruptionLevel: InterruptionLevel.active, // Ensure it breaks through
      ),
    );

    await flutterLocalNotificationsPlugin.show(
      id: id,
      title: normalizedTitle,
      body: normalizedBody,
      notificationDetails: notificationDetails,
    );
  }

  String _normalizeText(String value, {String fallback = ''}) {
    final collapsed = value.replaceAll(RegExp(r'\s+'), ' ').trim();
    return collapsed.isEmpty ? fallback : collapsed;
  }
}
