import 'package:flutter/material.dart';
import 'package:kerosene/design_system/icons.dart';

enum FlowSurface {
  mobile(Size(390, 844)),
  desktop(Size(1180, 760)),
  public(Size(1240, 780));

  final Size targetSize;

  const FlowSurface(this.targetSize);
}

class FlowItem {
  final String id;
  final String section;
  final String title;
  final String routeName;
  final IconData icon;
  final FlowSurface surface;

  const FlowItem({
    required this.id,
    required this.section,
    required this.title,
    required this.routeName,
    required this.icon,
    required this.surface,
  });
}

const storybookFlowItems = [
  FlowItem(
    id: 'auth-welcome',
    section: 'Entrada',
    title: 'Boas-vindas',
    routeName: '/welcome',
    icon: KeroseneIcons.home,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'auth-login',
    section: 'Entrada',
    title: 'Login',
    routeName: '/login',
    icon: KeroseneIcons.user,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'auth-recovery',
    section: 'Entrada',
    title: 'Recovery emergencial',
    routeName: '/recovery/emergency',
    icon: KeroseneIcons.passkey,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'auth-passkey',
    section: 'Entrada',
    title: 'Passkey',
    routeName: '/passkey',
    icon: KeroseneIcons.biometric,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'auth-signup',
    section: 'Entrada',
    title: 'Cadastro',
    routeName: '/signup',
    icon: KeroseneIcons.userCheck,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'auth-server',
    section: 'Entrada',
    title: 'Servidor indisponível',
    routeName: '/server-unavailable',
    icon: KeroseneIcons.serverUnavailable,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'mobile-loading',
    section: 'App Mobile',
    title: 'Carregamento',
    routeName: '/home_loading',
    icon: KeroseneIcons.pending,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'mobile-home',
    section: 'App Mobile',
    title: 'Home',
    routeName: '/home',
    icon: KeroseneIcons.wallet,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'mobile-card',
    section: 'App Mobile',
    title: 'Contas Bitcoin',
    routeName: '/accounts',
    icon: KeroseneIcons.wallet,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'bitcoin-advanced',
    section: 'App Mobile',
    title: 'Bitcoin Advanced',
    routeName: '/accounts',
    icon: KeroseneIcons.invoice,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'mobile-history',
    section: 'App Mobile',
    title: 'Extrato',
    routeName: '/activity',
    icon: KeroseneIcons.history,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'mobile-send',
    section: 'App Mobile',
    title: 'Enviar',
    routeName: '/send-money',
    icon: KeroseneIcons.send,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'mobile-settings',
    section: 'App Mobile',
    title: 'Configurações',
    routeName: '/settings',
    icon: KeroseneIcons.settings,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'mobile-notifications',
    section: 'App Mobile',
    title: 'Notificações',
    routeName: '/notifications',
    icon: KeroseneIcons.notifications,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'account-security',
    section: 'Conta',
    title: 'Segurança',
    routeName: '/account/security',
    icon: KeroseneIcons.security,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'account-notifications',
    section: 'Conta',
    title: 'Preferências de notificação',
    routeName: '/account/notifications',
    icon: KeroseneIcons.notifications,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'account-sovereignty',
    section: 'Conta',
    title: 'Status soberano',
    routeName: '/security/sovereignty',
    icon: KeroseneIcons.shield,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-selection',
    section: 'Receber',
    title: 'Seleção',
    routeName: '/receive',
    icon: KeroseneIcons.down,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-providers',
    section: 'Receber',
    title: 'Provedores',
    routeName: '/receive/providers',
    icon: KeroseneIcons.creditCard,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-requests-loading',
    section: 'Receber',
    title: 'Requests carregando',
    routeName: '/receive/requests/loading',
    icon: KeroseneIcons.pending,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-requests-empty',
    section: 'Receber',
    title: 'Requests vazio',
    routeName: '/receive/requests/empty',
    icon: KeroseneIcons.inbox,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-requests-pending',
    section: 'Receber',
    title: 'Request pendente',
    routeName: '/receive/requests/pending',
    icon: KeroseneIcons.pending,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-requests-paid',
    section: 'Receber',
    title: 'Request pago',
    routeName: '/receive/requests/paid',
    icon: KeroseneIcons.success2,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-requests-expired',
    section: 'Receber',
    title: 'Request expirado',
    routeName: '/receive/requests/expired',
    icon: KeroseneIcons.timerOff,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-requests-error',
    section: 'Receber',
    title: 'Requests erro',
    routeName: '/receive/requests/error',
    icon: KeroseneIcons.error,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-amount-qr',
    section: 'Receber',
    title: 'Valor para QR',
    routeName: '/receive/amount/qr',
    icon: KeroseneIcons.qr,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-amount-link',
    section: 'Receber',
    title: 'Valor para link',
    routeName: '/receive/amount/link',
    icon: KeroseneIcons.onchain,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-amount-nfc',
    section: 'Receber',
    title: 'Valor para NFC',
    routeName: '/receive/amount/nfc',
    icon: KeroseneIcons.nfc,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-qr',
    section: 'Receber',
    title: 'QR e dados',
    routeName: '/receive/qr',
    icon: KeroseneIcons.qr,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-onchain-confirming',
    section: 'Receber',
    title: 'Confirmações',
    routeName: '/receive/onchain-confirming',
    icon: KeroseneIcons.pending,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-onchain-identified',
    section: 'Receber',
    title: 'Pagamento identificado',
    routeName: '/receive/onchain-identified',
    icon: KeroseneIcons.success,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-nfc',
    section: 'Receber',
    title: 'NFC Kerosene',
    routeName: '/receive/nfc',
    icon: KeroseneIcons.nfc,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'receive-onchain-nfc',
    section: 'Receber',
    title: 'NFC on-chain',
    routeName: '/receive/onchain-nfc',
    icon: KeroseneIcons.nfc,
    surface: FlowSurface.mobile,
  ),
  FlowItem(
    id: 'public-landing',
    section: 'Web Público',
    title: 'Landing',
    routeName: '/public/landing',
    icon: KeroseneIcons.globe,
    surface: FlowSurface.public,
  ),
  FlowItem(
    id: 'public-download',
    section: 'Web Público',
    title: 'Download',
    routeName: '/public/download',
    icon: KeroseneIcons.download,
    surface: FlowSurface.public,
  ),
  FlowItem(
    id: 'public-status',
    section: 'Web Público',
    title: 'Status',
    routeName: '/public/status',
    icon: KeroseneIcons.activity,
    surface: FlowSurface.public,
  ),
  FlowItem(
    id: 'admin-login',
    section: 'Admin Web',
    title: 'Login admin',
    routeName: '/admin/login',
    icon: KeroseneIcons.passkey,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-dashboard',
    section: 'Admin Web',
    title: 'Dashboard',
    routeName: '/admin/dashboard',
    icon: KeroseneIcons.shares,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-monitoring',
    section: 'Admin Web',
    title: 'Monitoring',
    routeName: '/admin/monitoring',
    icon: KeroseneIcons.activity,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-transactions',
    section: 'Admin Web',
    title: 'Integrity Proofs',
    routeName: '/admin/transactions',
    icon: KeroseneIcons.biometric,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-lightning',
    section: 'Admin Web',
    title: 'Lightning',
    routeName: '/admin/lightning',
    icon: KeroseneIcons.lightning,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-onchain',
    section: 'Admin Web',
    title: 'On-chain',
    routeName: '/admin/onchain',
    icon: KeroseneIcons.onchain,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-checks',
    section: 'Admin Web',
    title: 'Hash Chain',
    routeName: '/admin/checks',
    icon: KeroseneIcons.network,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-payment-links',
    section: 'Admin Web',
    title: 'Payment Metrics',
    routeName: '/admin/payment-links',
    icon: KeroseneIcons.qr,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-analytics',
    section: 'Admin Web',
    title: 'Analytics',
    routeName: '/admin/analytics',
    icon: KeroseneIcons.gauge,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-volatility',
    section: 'Admin Web',
    title: 'Volatility',
    routeName: '/admin/volatility',
    icon: KeroseneIcons.trendUp,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-companies',
    section: 'Admin Web',
    title: 'Infrastructure',
    routeName: '/admin/companies',
    icon: KeroseneIcons.business,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-audit',
    section: 'Admin Web',
    title: 'Audit & Security',
    routeName: '/admin/audit',
    icon: KeroseneIcons.security,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-devices',
    section: 'Admin Web',
    title: 'Authenticated Devices',
    routeName: '/admin/authenticated-devices',
    icon: KeroseneIcons.device,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-notifications',
    section: 'Admin Web',
    title: 'Notifications',
    routeName: '/admin/notifications',
    icon: KeroseneIcons.notifications,
    surface: FlowSurface.desktop,
  ),
  FlowItem(
    id: 'admin-settings',
    section: 'Admin Web',
    title: 'Settings',
    routeName: '/admin/settings',
    icon: KeroseneIcons.settings,
    surface: FlowSurface.desktop,
  ),
];
