// ignore_for_file: use_key_in_widget_constructors, unused_import, unused_element

export 'dart:async' hide AsyncError;
export 'dart:math' show min, max, Random, pi, sin, cos;

export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:flutter_animate/flutter_animate.dart';
export 'package:flutter_riverpod/flutter_riverpod.dart';
export 'package:flutter_riverpod/legacy.dart';
export 'package:kerosene/design_system/icons.dart';
export 'package:kerosene/core/l10n/l10n_extension.dart';
export 'package:kerosene/core/motion/app_motion.dart';
export 'package:kerosene/core/navigation/app_page_transitions.dart';
export 'package:kerosene/core/navigation/deferred_page.dart';
export 'package:kerosene/core/presentation/widgets/app_notice.dart';
export 'package:kerosene/core/presentation/widgets/app_notification_surface.dart';
export 'package:kerosene/core/presentation/widgets/app_primary_navigation.dart';
export 'package:kerosene/core/presentation/widgets/kerosene_logo.dart';
export 'package:kerosene/core/presentation/widgets/kerosene_logo_loading_view.dart';
export 'package:kerosene/core/presentation/widgets/tor_loading_dots.dart';
export 'package:kerosene/core/providers/currency_provider.dart';
export 'package:kerosene/core/providers/price_provider.dart';
export 'package:kerosene/core/providers/shared_preferences_provider.dart';
export 'package:kerosene/core/responsive/kerosene_responsive.dart';
export 'package:kerosene/core/theme/app_colors.dart';
export 'package:kerosene/core/theme/app_spacing.dart';
export 'package:kerosene/core/theme/app_typography.dart';
export 'package:kerosene/core/utils/money_display.dart';
export 'package:kerosene/core/utils/qr_payment_parser.dart';
export 'package:kerosene/shared/widgets/state_feedback_view.dart';
export 'package:kerosene/shared/widgets/bitcoin_refresh_indicator.dart';
export 'package:kerosene/shared/widgets/bouncing_button_wrapper.dart';
export 'package:kerosene/features/financial_accounts/domain/entities/wallet.dart';
export 'package:kerosene/features/movement/domain/entities/transaction.dart';
export 'package:kerosene/features/movement/domain/entities/payment_link.dart';
export 'package:kerosene/features/movement/domain/entities/tx_status.dart';
export 'package:kerosene/features/movement/providers/transaction_provider.dart';
export 'package:kerosene/features/movement/widgets/statement_transaction_card.dart';
export 'package:kerosene/features/financial_accounts/presentation/providers/wallet_provider.dart'
    hide transactionRepositoryProvider;
export 'package:kerosene/features/financial_accounts/presentation/providers/balance_websocket_provider.dart';
export 'package:kerosene/features/financial_accounts/presentation/providers/balance_settings_provider.dart';
export 'package:kerosene/features/financial_accounts/presentation/state/wallet_state.dart';
export 'package:kerosene/features/auth/controller/auth_controller.dart';
export 'package:kerosene/features/movement/widgets/receive_flow_ui.dart';
export 'package:kerosene/features/financial_accounts/presentation/widgets/wallet_flow_selector.dart';
export 'package:kerosene/features/home/presentation/widgets/animated_balance_display.dart';
export 'package:kerosene/features/notifications/domain/entities/session_notification_item.dart';
export 'package:kerosene/features/notifications/presentation/providers/session_notification_provider.dart';
export 'package:kerosene/features/notifications/presentation/notification_navigation.dart';
export 'package:kerosene/features/notifications/presentation/notification_visuals.dart';
export 'package:kerosene/features/notifications/presentation/screens/notification_center_screen.dart';
